## create makeCacheMatrix.object for storing cached data
makeCacheMatrix <- function(x = matrix()) {
  #copied from https://www.coursera.org/learn/r-programming/discussions/forums/_ZerTCj2EeaZ8Apto8QB_w/threads/mowodw4rEemS0Q4U5mc4kg
  #nothing to see here
  cachedInv <- NULL
  set <- function(newMatrix) {
    x <<- newMatrix
    cachedInv <<- NULL
  }
  get <- function() x
  setInv <- function(invResult) cachedInv <<- invResult
  getInv <- function() cachedInv
  list(set = set, get = get,
       setInv = setInv,
       getInv = getInv)
}

## input = object generated by function makeCacheMatrix(x)
## output = inverse of matrix x
cacheSolve <- function(x, ...) {
  cachedResult <- x$getInv()
  if(!is.null(cachedResult)) {
    message("getting cached data") 
    #if cached result exists then get the cached result
    return(cachedResult)
  }
  #if cached result does not exist then calculate and cache new one
  originalMatrix <- x$get()
  InvResult <- solve(originalMatrix)
  x$setInv(InvResult)
  InvResult
  # originalMatrix %*% InvResult should result in Identity Matrix
}

#test to see that originalMatrix %*% InvResult actually give identity matrix
test1 <- function(){
  a = matrix(runif(9),3)
  message("matrix a is: ")
  print(a)
  aa = makeCacheMatrix(a)
  cacheSolve(aa)
  message("inverse of a is:")
  print(aa$getInv())
  message("a %*% inverse of a is:")
  result = a %*% aa$getInv()
  #print with rounding to 15 digits
  print(round(result,15))
         
}
